### ISSUE TITLE
Dear author, when will the source code be released？

### ISSUE THREAD

**Issue by WangzcBruce** [ryhnhao/RCooper#1]
Eagerly looking forward to this project!!

**Comment by ryhnhao** [comment]
Expect the middle of March, definitely before the end of March.
Besides, the codebase may be transfer to another rep, I will update this info to you by email!

**Comment by WangzcBruce** [comment]
Thanks for your reply! By the way, is there an available link to your awesome paper?

**Comment by ryhnhao** [comment]
We will release our arXiv paper before Mar. 10.
Recently we have supplemented some new data, so we are trying to update benchmark results in paper.

Thanks for your attention!

**Comment by WangzcBruce** [comment]
I am sorry to bother you again, but I am having difficulty obtaining the RCooper datasets. I have requested them several times, but have not received any replies. /(ㄒoㄒ)/~~
[image](https://github.com/ryhnhao/RCooper/assets/45158420/493b336b-83ad-4dd2-bdf8-0e6558beecbb)

**Comment by ryhnhao** [comment]
Unfortunately, as far as we know, patient waiting seems to be the only way.
As an academic institution, our group does not have authority to release data.

Constrained by signed contract, [CAIC website](https://www.t3caic.com/qingzhen/) is the only official website for Dataset Release.

I'm sorry that I can't help you more in this case.

**Comment by ryhnhao** [comment]
@WangzcBruce 
Hi, Bruce
we have release the codebase in [https://github.com/AIR-THU/DAIR-RCooper](https://github.com/AIR-THU/DAIR-RCooper),
and the arxiv paper is published in [https://arxiv.org/abs/2403.10145](https://arxiv.org/abs/2403.10145).
Thanks for your attention.
