### ISSUE TITLE
很棒的工作

### ISSUE THREAD

**Issue by JerryBryant24** [ryhnhao/RCooper#2]
很棒的工作，期待作者的更新。跟大佬一起学习！！！

**Comment by ryhnhao** [comment]
@JerryBryant24
Hello
we have release the codebase in [https://github.com/AIR-THU/DAIR-RCooper](https://github.com/AIR-THU/DAIR-RCooper),
and the arxiv paper is published in [https://arxiv.org/abs/2403.10145](https://arxiv.org/abs/2403.10145).
Thanks for your attention.
