### ISSUE TITLE
When can be viewed online for this paper?

### ISSUE THREAD

**Issue by huishuaixiong** [ryhnhao/RCooper#3]

**Comment by ryhnhao** [comment]
Thanks for your attention. The arxiv paper and codebase will be announced at Mon, 18 Mar.

**Comment by ryhnhao** [comment]
@huishuaixiong 
Hi, Shuaixiong
we have release the codebase in [https://github.com/AIR-THU/DAIR-RCooper](https://github.com/AIR-THU/DAIR-RCooper),
and the arxiv paper is published in [https://arxiv.org/abs/2403.10145](https://arxiv.org/abs/2403.10145).
Thanks for your attention.
